source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TimeCamouflage_Example', :exclusive => true do
  pod "TimeCamouflage", :path => "../"
end

target 'TimeCamouflage_Tests', :exclusive => true do
  pod "TimeCamouflage", :path => "../"
  pod 'Quick', '~> 0.6.0'
  pod 'Nimble', '2.0.0-rc.3'
end
